cloud:
  aws:
    credentials:
      accessKey: AKIA53TREN5DRUAD5ZMV
      secretKey: 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
    s3:
      bucket: eagle25-freelec-springboot-attachments
      dir: /dev
    region:
      static: us-east-1
    stack:
      auto: false
